[project]
name = "benchmarking"
version = "0.1.0"
description = ""
authors = [
    { name = "azurwastaken", email = "caseaux.maxime@gmail.com" }
]
requires-python = ">3.10,<4.0"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
